spring:
  autoconfigure:
    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#      - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration
#      - org.springframework.cloud.netflix.eureka.EurekaDiscoveryClientConfiguration
#      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
#      - org.springframework.cloud.consul.serviceregistry.ConsulAutoServiceRegistrationAutoConfiguration
#      - org.springframework.cloud.consul.discovery.ConsulCatalogWatchAutoConfiguration
#      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
#      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
#      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration

  liquibase.change-log: classpath:db/changelog/master.yml

microzoo:
  request-delay: ~
  response-delay: ~
